[[main]]
  identifier = "about"
  name = "About us"
  url = "about"
  weight = 1

[[main]]
  identifier = "youtube"
  name = "Youtube Channel"
  url = "youtube"
  weight = 2

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 3

[[main]]
  identifier = "events"
  name = "Events"
  url = "events"
  weight = 4